### ISSUE TITLE
State Tool stopped working due to nil pointer in locale package

### ISSUE THREAD

**Issue by sailormoon22** [ActiveState/cli#1438]
Hi
When I launche state utility I ger an error. I've tried to reinstall this utility and I got the same error:

```
Rollbar error: empty token
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x83cd35]

goroutine 1 [running]:
github.com/ActiveState/cli/internal/locale.T(0x14b0a58, 0x15, 0x0, 0x0, 0x0, 0x1650400, 0x8)
        /home/runner/work/cli/cli/internal/locale/locale.go:119 +0x55
github.com/ActiveState/cli/internal/language.init()
        /home/runner/work/cli/cli/internal/language/language.go:69 +0x47
```

This problem appeared just today.

**Comment by Naatan** [comment]
Hi @sailormoon22, thanks for reaching out. Would you be able to run the same command again but this time prefixed with `VERBOSE=true`, eg. `VERBOSE=true state activate`. Then share the output.

**Comment by sailormoon22** [comment]
I inputed:

`VERBOSE=true state activate`

and got the same result:

`Rollbar error: empty token
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x83cd35]

goroutine 1 [running]:
github.com/ActiveState/cli/internal/locale.T(0x14b0a58, 0x15, 0x0, 0x0, 0x0, 0x1650400, 0x8)
        /home/runner/work/cli/cli/internal/locale/locale.go:119 +0x55
github.com/ActiveState/cli/internal/language.init()
        /home/runner/work/cli/cli/internal/language/language.go:69 +0x47`

**Comment by Naatan** [comment]
Sorry, could you share the full output of that command?

**Comment by sailormoon22** [comment]
This is already the full output.
![Безымянный2](https://user-images.githubusercontent.com/86061260/124881393-f6697080-dfd7-11eb-9cee-8267619d81e0.png)

**Comment by Naatan** [comment]
Could you try resetting your internal config file by running `state clean config`?

You'll have to login again, but otherwise there isn't a whole lot in that file that is crucial to the operation of the state tool and it could be what's causing issues here. Hard to say for certain since the backtrace is incomplete.

**Comment by sailormoon22** [comment]
Every command of state utility fail :
![Безымянный2](https://user-images.githubusercontent.com/86061260/125061665-3acb3e00-e0b6-11eb-9ee9-2e59b7b238e8.png)

**Comment by sailormoon22** [comment]
I found the log files on my system.
This is its content:
```
[ERROR Jul  9 13:05:29.429853531, defaults.go:149] Could not load configuration: Failed to load configuration.

Stacktrace: /home/runner/work/cli/cli/internal/logging/logging.go:github.com/ActiveState/cli/internal/logging.Error:258
/home/runner/work/cli/cli/internal/logging/defaults.go:github.com/ActiveState/cli/internal/logging.init.0:149
/opt/hostedtoolcache/go/1.15.11/x64/src/runtime/proc.go:runtime.doInit:5652
/opt/hostedtoolcache/go/1.15.11/x64/src/runtime/proc.go:runtime.doInit:5647
/opt/hostedtoolcache/go/1.15.11/x64/src/runtime/proc.go:runtime.doInit:5647
/opt/hostedtoolcache/go/1.15.11/x64/src/runtime/proc.go:runtime.main:191
/opt/hostedtoolcache/go/1.15.11/x64/src/runtime/asm_amd64.s:runtime.goexit:1374

[DEBUG Jul  9 13:05:29.430017525, defaults.go:178] Args: [/usr/local/bin/state _prepare]
[DEBUG Jul  9 13:05:29.430787309, locale.go:34] Init
```

**Comment by Naatan** [comment]
Ahh yeah, so it's definitely the config file at fault here. 

Use these docs to locate your config directory: https://docs.activestate.com/platform/state/troubleshooting/

Then delete the config.yml file from that directory. Once you do that your commands should start working again.

We are actively working towards a fix for this issue, apologies for the inconvenience.

**Comment by sailormoon22** [comment]
Thank you! All work now)
Should I close the issue?

**Comment by Naatan** [comment]
I'll go ahead and close it. Thanks for reporting your issue, this will be addressed in our next release. If you run into it again before that happens please delete the config file again.
