### ISSUE TITLE
Segmentation Fault on arm64 Mac

### ISSUE THREAD

**Issue by gscho** [ActiveState/cli#2241]
After running:

`sh <(curl -q https://platform.activestate.com/dl/cli/w19880m01/install.sh)`

I'm seeing a seg fault when I run `state --help`

```bash
1]    14566 segmentation fault  state --help
```

**Comment by Naatan** [comment]
Hi there. This is an issue with us using UPX to compress our executables. M1 Macs starting with Ventura would result in the above error message.

We have a new version releasing soon, it's on the beta channel but has already gone through a significant amount of testing:

```
sh <(curl -q https://raw.githubusercontent.com/ActiveState/cli/beta/installers/install.sh) -b beta
```
